In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
arr_1d=np.arange(10,51)
print(arr_1d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [8]:
random_arr=np.random.random((3,3))
print(random_arr)

[[0.43039701 0.61050449 0.67675401]
 [0.91895799 0.52832193 0.38973498]
 [0.75969594 0.59729675 0.95596277]]


In [14]:
print("Shape:",np.shape(random_arr))

Shape: (3, 3)


In [15]:
print("Size:",np.size(random_arr))

Size: 9


In [17]:
print("Datatypes:",random_arr.dtype)

Datatypes: float64


In [19]:
arr_add_5=arr_1d+5
print("Original array:",arr_1d)
print("Array after adding 5:",arr_add_5)

Original array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Array after adding 5: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [26]:
arr_2d=np.array([[1,2],[3,4]])
arr2_2d=np.array([[2,3],[1,4]])
print(arr_2d*arr2_2d)

[[ 2  6]
 [ 3 16]]


In [27]:
import numpy as np
array_5x5 = np.arange(1, 26).reshape(5, 5)
first_row = array_5x5[0, :]
last_column = array_5x5[:, -1]
subarray = array_5x5[:3, :2]
print("Array 5x5:")
print(array_5x5)
print("\nFirst Row:")
print(first_row)
print("\nLast Column:")
print(last_column)
print("\nSubarray (first three rows and first two columns):")
print(subarray)

Array 5x5:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

First Row:
[1 2 3 4 5]

Last Column:
[ 5 10 15 20 25]

Subarray (first three rows and first two columns):
[[ 1  2]
 [ 6  7]
 [11 12]]


In [28]:
import numpy as np
random_array = np.random.randint(1, 101, size=10)
max_value = np.max(random_array)
min_value = np.min(random_array)
mean_value = np.mean(random_array)
std_dev_value = np.std(random_array)
print("Array:", random_array)
print("Maximum value:", max_value)
print("Minimum value:", min_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev_value)

Array: [ 8 42 44 69 80 16 66 43 26 48]
Maximum value: 80
Minimum value: 8
Mean value: 44.2
Standard deviation: 21.97635092548351


In [33]:
arr_1d=np.arange(1,13)
print(arr_1d)
arr_reshape=np.array(arr_1d).reshape(3,4)
print(arr_reshape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
arr_ones=np.ones((3,3))
print(arr_ones)
arr=np.array([1,2,3])
result_arr=arr_ones+arr
print("Result Matrix is:\n",result_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Result Matrix is:
 [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [40]:
import numpy as np
random_array = np.random.randint(1, 51, size=10)
divisible_by_5 = random_array[random_array % 5 == 0]
print("Random Array:")
print(random_array)
print("\nElements divisible by 5:")
print(divisible_by_5)

Random Array:
[37 14 49  6  8  9  9 16  7 41]

Elements divisible by 5:
[]


In [43]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,3],[2,4]])
print("Matrix A:",A)
print("Matrix B:",B)
result=np.matmul(A,B)
print("Multiplication matrix:\n",result)

Matrix A: [[1 2]
 [3 4]]
Matrix B: [[1 3]
 [2 4]]
Multiplication matrix:
 [[ 5 11]
 [11 25]]


In [44]:
import numpy as np
array_4x4 = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])
diagonal_elements = array_4x4[np.arange(4), np.arange(4)]
print("4x4 Array:")
print(array_4x4)
print("\nDiagonal Elements:")
print(diagonal_elements)

4x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Diagonal Elements:
[ 1  6 11 16]
